public class primitiveDataTypeDemo {
    public void printBasicDataType(){

       Object obj= 'This is a string';
       Object obj2 = 10;
       
       ID id1 ='001D000000Ju1zH';
       
       system.debug('obj: '+obj);
       system.debug('obj2: '+obj2);
       system.debug('ID: '+id1);
       
       
       
        // Decimal decValue = 27.01;
        // system.debug('Decimal: '+decValue);

        // Long longValue = 2147483648L;
        // system.debug('Long: '+longValue);
        // string batchName= 'Falcons';
        // Integer totalCandidates = 40;
        // boolean isAdminCompleted = true;
        // string batchDescription = batchName + ' are the best.';
        // system.debug(batchDescription);

        // system.debug('batch name is '+batchName);
        // system.debug('total # of candidates: '+totalCandidates);
        // system.debug('admin completed? '+isAdminCompleted);
        
    }
}
