List<Integer>  l1= new list<integer>{10,15,21,99,55,44,10,99};
set<integer> set3 = setDemo.setFromList(l1);
system.debug('set 3= '+set3); 

set<string> cities = new Set<String>();
cities.add('Tokyo');
cities.add('Lisbon');
cities.add('Berlin');
cities.add('nairobi');
cities.add('Tokyo');
cities.add('tOkyo');
cities.add('tOkyo');
cities.add('Berlin');

set<string> citiesCaps =SetDemo.capitalizeSet(cities);
system.debug(citiesCaps);
